PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# My ontology
PREFIX poc: <http://www.semanticweb.org/donald/ontologies/2024/9/estoppoc#>

# Requirement 3.1: Each machine has an e-stop
# Violation: a machine which does not have an attachedEStop.

SELECT ?machine
WHERE {
  {
    ?machine a poc:Machine .
  }
  MINUS
  {
    ?machine a poc:Machine .
    ?estop a poc:EStop .
    ?machine poc:hasEStop ?estop .
  }
}