PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# My ontology
PREFIX poc: <http://www.semanticweb.org/donald/ontologies/2024/9/estoppoc#>

# Requirement 3.2.1: Each connected control panel has a red/yellow e-stop
# Violation: A RCP which is connected and has an e-stop which has r/y == false

SELECT ?controlPanel
WHERE {
  ?controlPanel a poc:RemovableControlPanel .
  ?controlPanel poc:isConnectedTo ?safetyNetwork .
  ?controlPanel poc:hasColorChangingEStop ?estop .
  ?estop a poc:ColorChangingEStop .
  ?estop poc:isRedYellow false .
}