PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# My ontology
PREFIX poc: <http://www.semanticweb.org/donald/ontologies/2024/9/estoppoc#>


# Requirement 4.2: Registered devices do not disconnect
# Violation: a Device which is registered and not connected.

SELECT ?device
WHERE {
  {
    ?device a poc:Device .
    ?device poc:isRegisteredBy ?registrationArray .
  }
  MINUS
  {
    ?device a poc:Device .
    ?device poc:isConnectedTo ?connectionArray .
  }
}